apiVersion: runwhen.com/v1
kind: Workflow
metadata:
  name: {{slx_name}}-pvc-alert-workflow
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  fromActivities:
  - displayName: RunWhen ACR Image Update Workflow
    description: Run tasks to update ACR when new RunWhen container images are available. 
    actions:
    - tasks:
        slx: {{slx_name.split('--')[1]}}
        titles:
          - '*'
        sessionTTL: 20m
    match:
      activityVerbs:
      - SLI_ALERTS_STARTED
      slxs:
      - {{slx_name.split('--')[1]}}
    name: {{slx_name.split('--')[1]}}-runwhen-acr-image-update-workflow