apiVersion: runwhen.com/v1
kind: ServiceLevelX
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  imageURL: https://storage.googleapis.com/runwhen-nonprod-shared-images/icons/runwhen_icon.png
  alias: RunWhen Local Helm Image Updates
  asMeasuredBy: Count of images that require update. 
  configProvided:
  - name: OBJECT_NAME
    value: {{match_resource.resource.metadata.name}}
  owners:
  - {{workspace.owner_email}}
  statement: RunWhen Local deployed images should be up to date. 
  additionalContext:  
    resource: "{{ resource }}"
