apiVersion: runwhen.com/v1
kind: ServiceLevelIndicator
metadata:
  name: {{slx_name}}
  labels:
    {% include "common-labels.yaml" %}
  annotations:
    {% include "common-annotations.yaml" %}
spec:
  displayUnitsLong: Count
  displayUnitsShort: "#"
  locations:
    - {{default_location}}
  description: Counts the number of RW images that need updating in ACR
  codeBundle:
    {% if repo_url %}
    repoUrl: {{repo_url}}
    {% else %}
    repoUrl: https://github.com/runwhen-contrib/rw-workspace-utils.git
    {% endif %}
    {% if ref %}
    ref: {{ref}}
    {% else %}
    ref: main
    {% endif %}
    pathToRobot: codebundles/azure-rw-acr-helm-update/sli.robot
  intervalStrategy: intermezzo
  intervalSeconds: 600
  configProvided:
    - name: REGISTRY_NAME
      value: "{{custom.azure_acr_registry}}"
    - name: REPOSITORY_ROOT_PATH
      value: "runwhen"
    - name: HELM_APPLY_UPGRADE
      value: "true"
    - name: HELM_RELEASE
      value: {{match_resource.resource.metadata.annotations.get('meta.helm.sh/release-name', None)}}
    - name: NAMESPACE
      value: {{match_resource.resource.metadata.namespace}}
    - name: CONTEXT
      value: {{context}}
    - name: AZURE_RESOURCE_SUBSCRIPTION_ID
      value: "{{ custom.azure_acr_registry_subscriptionId }}"
  secretsProvided:
    {% include "kubernetes-auth.yaml" ignore missing %}
    {% include "azure-auth.yaml" ignore missing %}
  alerts:
    warning:
      operator: ">="
      threshold: '1'
      for: '20m'
